name: Fetch and Process RSS Feed
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 7-23 * * *'
jobs:
  fetch-feed:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 必要なNode.jsのバージョンを指定
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
      - name: Install dependencies
        run: npm install
      - name: Exists dotfile
        run: ls -la /home/runner/
      - name: Run fetchFeed script
        run: node fetchFeed.js
