name: Fetch and Process RSS Feed
on:
  schedule:
    - cron: '*/6 0-9 * * *'
  workflow_dispatch:
jobs:
  fetch-feed:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 必要なNode.jsのバージョンを指定
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
      - name: Install dependencies
        run: npm install
      - name: Restore seen articles
        uses: actions/cache@v4.2.0
        with:
          path: /home/runner/.seenArticles.json
          key: ${{ runner.os }}-seen-articles
      - name: Before Articles Count
        run: cat /home/runner/.seenArticles.json | wc
      - name: Run fetchFeed script
        run: node fetchFeed.js
      - name: After Articles Count
        run: cat /home/runner/.seenArticles.json | wc
      - name: Cache seen articles
        uses: actions/cache@v4.2.0
        with:
          path: /home/runner/.seenArticles.json
          key: ${{ runner.os }}-seen-articles
