name: Fetch and Process RSS Feed
on:
  schedule:
    - cron: '*/15 7-23 * * *'
jobs:
  fetch-feed:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 必要なNode.jsのバージョンを指定
      - name: Where echo
          run: which echo
      - name: Do echo
          run: echo Hello
      - name: Install curl
          run: sudo apt-get update && sudo apt-get install -y curl
      - name: Where curl
          run: which curl
      - name: Install dependencies
        run: npm install
      - name: Run fetchFeed script
        run: node fetchFeed.js
