name: Install and Run Piping Server
on:
  workflow_dispatch:
jobs:
  fetch-feed:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 必要なNode.jsのバージョンを指定
      - name: Install Piping Server
        run: npm install -g piping-server
      - name: Run Piping Server
        run: piping-server
